[package]
name = "future"
version = "0.1.0"
authors = ["lintanghui <lintanghui@bilibili.com>"]
edition = "2018"

[dependencies]
futures="0.1"
tokio="0.1"
[[bin]]
name="oneshot"
path="bin/oneshot.rs"
[[bin]]
name="mpsc"
path="bin/mpsc.rs"
[lib]
name="lfuture"
path="src/lib.rs"