[workspace]
members=[
    "common_set",
    "data_type",
    "enumerate",
    "function",
    "ownship",
    "structs",
    "smart_point",
    "variable",
    "concurrency",
    "kv",
    "stream",
    "future",
]

